server:
  port: ${MOCK_ORDER_SERVICE_PORT:8082}
spring:
  application:
    name: mock-order-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
        namespace: ${NACOS_NAMESPACE}
        group: ${NACOS_GROUP}
springdoc:
  api-docs:
    path: /v3/api-docs
mock:
  order:
    slow-response-delay: ${MOCK_ORDER_SLOW_RESPONSE_DELAY:PT16S}
